"""
Текстовые константы бота.
"""

HELP_TEXT = (
    "Привет! Я бот для автоматической отправки постов по маршрутам.\n"
    "Используй команды ниже.\n\n"
    "Все команды управления доступны только администратору.\n\n"
    "<b>📚 Управление чатами/топиками:</b>\n"
    "<code>/add_chat &lt;имя&gt; &lt;tg_chat_id&gt; [tg_topic_id]</code> — зарегистрировать чат/топик\n"
    "<code>/chats</code> — список всех зарегистрированных чатов\n"
    "<code>/rename_chat &lt;id&gt; &lt;новое_имя&gt;</code> — переименовать\n"
    "<code>/freeze_chat &lt;id&gt;</code> — заморозить чат (отключить)\n"
    "<code>/unfreeze_chat &lt;id&gt;</code> — разморозить чат\n"
    "<code>/toggle_sendable &lt;id&gt;</code> — переключить флаг «можно отправлять» (для целей)\n"
    "<code>/delete_chat &lt;id&gt;</code> — удалить чат (если не используется)\n\n"
    "<b>🛣️ Управление маршрутами:</b>\n"
    "<code>/routes</code> — список маршрутов\n"
    "<code>/add_route &lt;имя_исх&gt; &lt;имя_цели&gt;</code> — пошаговое добавление\n"
    "<code>/add_route &lt;имя_исх&gt; &lt;имя_цели&gt; &lt;ЧЧ:ММ&gt; &lt;интервалы&gt;</code> — однострочное\n"
    "<code>/send_now &lt;ID&gt;</code> — отправить пост сейчас\n"
    "<code>/rename_route &lt;ID&gt; &lt;новое_название&gt;</code> — переименовать маршрут\n"    
    "<code>/delete_route &lt;ID&gt;</code> — удалить маршрут\n"
    "<code>/freeze_route &lt;ID&gt;</code> — заморозить маршрут\n"
    "<code>/unfreeze_route &lt;ID&gt;</code> — разморозить маршрут\n"
    "<code>/edit_time &lt;ID&gt; &lt;ЧЧ:ММ&gt;</code> — изменить время\n"
    "<code>/edit_intervals &lt;ID&gt; &lt;интервалы&gt;</code> — изменить интервалы\n"
    "<code>/edit_jitter &lt;ID&gt; &lt;секунды&gt;</code> — изменить разброс\n"
    "<code>/skip_next &lt;ID&gt;</code> — пропустить ближайшую публикацию\n\n"
    "<code>/toggle_random &lt;ID&gt;</code> — вкл/выкл случайную рассылку по sendable-чатам (для источника)\n"
    "<code>/add_target &lt;ID&gt; &lt;имена_чатов&gt;</code> — добавить цели (через запятую)\n"
    "<i>Спец. значения:</i> <code>all</code> (все активные чаты) или <code>sendable</code> (только sendable)\n\n"
    "<code>/remove_target &lt;ID маршрута&gt; &lt;имя_чата&gt;</code> — убрать цель из маршрута\n"
    "<i>Спец. значения:</i> <code>all</code> (все цели) или <code>sendable</code> (все sendable-чаты из целей)\n\n"
    "<b>📥 Импорт сообщений:</b>\n"
    "<code>/import_message &lt;ID маршрута&gt; &lt;ID сообщения&gt;</code>\n"
    "<code>/import_range &lt;ID маршрута&gt; &lt;начальный ID&gt; &lt;конечный ID&gt;</code>\n\n"
    "<b>Отмена:</b> /cancel\n\n"
    "<b>💡 Подсказки:</b>\n"
    "Имена чатов должны быть уникальными\n"
    "<code>0</code> вместо tg_topic_id — общий поток (без топика)\n"
    "Флаг «sendable» отмечает чаты, куда можно отправлять (для массовой рассылки)\n\n"
    "<b>📢 Singular-маршруты (реклама):</b>\n"
    "<code>/add_singular &lt;имя_источника&gt; &lt;ЧЧ:ММ&gt; &lt;интервалы&gt; [rounds]</code> — создать singular-маршрут\n"
    "<code>/list_singular</code> — список singular-маршрутов\n"
    "<code>/set_rounds &lt;ID&gt; &lt;N&gt;</code> — установить количество кругов (-1 = бесконечно)\n"
    "<code>/extend_route &lt;ID&gt; &lt;N&gt;</code> — продлить маршрут на N кругов\n"
    "<code>/get_rounds &lt;ID&gt;</code> — показать статус кругов\n\n"
)